blueprint:
  name: 'Tdsadasdasdasdas1'
  description: |
   dsadsa
  domain: automation
  input:
    topic:
      name: Tasmota MQTT Topic 
      description: "Found in Information tab of the webUI. Warning, it is case sensitive!"
      selector: 
        text:
    mac_address:
      name: Tasmota MAC Address
      description: "Found in Tasmota webUI Information tab."

mode: single
max_exceeded: silent

variables:
  topic: !input topic
  mac_address: !input mac_address
  macaddr: '{{- mac_address.split(":") | join -}}'
  payload_cookbook: >-
     {{ '{"name":"Set Cookbook","state_topic":"' ~ topic ~ '/cookbook","options":["Default","Custom","Fries","Frozen Fries","Nuggets","Chicken","Steak","Fish"],"value_template":"{%set m=value|int%}{%if m==0%}Default{%elif m==1%}Custom{%elif m==2%}Fries{%elif m==3%}Frozen Fries{%elif m==4%}Nuggets{%elif m==5%}Chicken{%elif m==6%}Steak{%elif m==7%}Fish{%else%}Unknown{%endif%}","command_topic":"cmnd/' ~ topic ~ '/event","icon":"mdi:chef-hat","availability_topic":"tele/' ~ topic ~'/LWT","pl_avail":"Online","pl_not_avail":"Offline","unique_id":"' ~ macaddr ~ '_cookbook","device":{"cns":[["mac","' ~ macaddr ~ '"]]}}' }}
  payload_cooktime: >-
     {{ '{"name":"Set Cooking Time","state_topic":"' ~ topic ~ '/cooktime","command_topic":"cmnd/' ~ topic ~ '/var5","icon":"mdi:av-timer","availability_topic":"tele/' ~ topic ~ '/LWT","pl_avail":"Online","pl_not_avail":"Offline","min":1,"max":60,"unique_id":"' ~ macaddr ~ '_cooktime","device":{"cns":[["mac","' ~ macaddr ~ '"]]}}' }}
  payload_cooktemp: >-
     {{ '{"name":"Set Cooking Temp","state_topic":"' ~ topic ~ '/cooktemp","command_topic":"cmnd/' ~ topic ~ '/var3","icon":"mdi:thermometer","availability_topic":"tele/' ~ topic ~ '/LWT","pl_avail":"Online","pl_not_avail":"Offline","min":40,"max":400,"unique_id":"' ~ macaddr ~ '_cooktemp","device":{"cns":[["mac","' ~ macaddr ~ '"]]}}' }}

trigger_variables:
  topic: !input topic

trigger:
	- platform: mqtt
	topic: 'tele/tasmota_zbbridge/SENSOR'

condition:
	- condition: template
	value_template: >
		{{ 'Occupancy' in ((trigger.payload_json.ZbReceived.values() | list)[0].keys() | list) }}

action:
	- service: mqtt.publish
	data_template:
	topic: homeassistant/binary_sensor/{{ (trigger.payload_json.ZbReceived.keys() | list)[0] }}Occupancy/config
	retain: true
	payload: >
		{% set code = (trigger.payload_json.ZbReceived.keys() | list)[0] %}
		{
			"name": "{{ trigger.payload_json.ZbReceived[code].Name }} Motion",
			"device_class": "motion",
			"state_topic": "tele/zigbee/{{ (trigger.payload_json.ZbReceived.keys() | list)[0] }}/Occupancy",
			"payload_off": "0",
			"payload_on": "1"
		}
	- service: mqtt.publish
	data_template:
		topic: > 
			tele/zigbee/{{ (trigger.payload_json.ZbReceived.keys() | list)[0] }}/Occupancy
		payload: >
			{% set code = (trigger.payload_json.ZbReceived.keys() | list)[0] %}
			{{ trigger.payload_json.ZbReceived[code].Occupancy }}
		retain: true
